// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: struct_tags.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/liov/protopatch2/patch/gopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MessageWithTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" test:"value"`
}

func (x *MessageWithTags) Reset() {
	*x = MessageWithTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_tags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithTags) ProtoMessage() {}

func (x *MessageWithTags) ProtoReflect() protoreflect.Message {
	mi := &file_struct_tags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithTags.ProtoReflect.Descriptor instead.
func (*MessageWithTags) Descriptor() ([]byte, []int) {
	return file_struct_tags_proto_rawDescGZIP(), []int{0}
}

func (x *MessageWithTags) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OuterMessageWithTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OuterMessageWithTags) Reset() {
	*x = OuterMessageWithTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_tags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OuterMessageWithTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterMessageWithTags) ProtoMessage() {}

func (x *OuterMessageWithTags) ProtoReflect() protoreflect.Message {
	mi := &file_struct_tags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessageWithTags.ProtoReflect.Descriptor instead.
func (*OuterMessageWithTags) Descriptor() ([]byte, []int) {
	return file_struct_tags_proto_rawDescGZIP(), []int{1}
}

type MessageWithOverrideTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1   string `protobuf:"bytes,1,opt,name=value1,proto3" json:"value1" test:"value"`
	Value2   string `protobuf:"bytes,2,opt,name=value2,proto3" json:"-" test:"value"`
	Value3   string `protobuf:"bytes,3,opt,name=value3,proto3" test:"value" json:"value"`
	Protobuf string `json:"protobuf,omitempty" protobuf:"bytes,4,opt,name=proto,proto3" test:"value"`
}

func (x *MessageWithOverrideTag) Reset() {
	*x = MessageWithOverrideTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_tags_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageWithOverrideTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithOverrideTag) ProtoMessage() {}

func (x *MessageWithOverrideTag) ProtoReflect() protoreflect.Message {
	mi := &file_struct_tags_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithOverrideTag.ProtoReflect.Descriptor instead.
func (*MessageWithOverrideTag) Descriptor() ([]byte, []int) {
	return file_struct_tags_proto_rawDescGZIP(), []int{2}
}

func (x *MessageWithOverrideTag) GetValue1() string {
	if x != nil {
		return x.Value1
	}
	return ""
}

func (x *MessageWithOverrideTag) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

func (x *MessageWithOverrideTag) GetValue3() string {
	if x != nil {
		return x.Value3
	}
	return ""
}

func (x *MessageWithOverrideTag) GetProtobuf() string {
	if x != nil {
		return x.Protobuf
	}
	return ""
}

type OuterMessageOverrideTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OuterMessageOverrideTag) Reset() {
	*x = OuterMessageOverrideTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_tags_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OuterMessageOverrideTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterMessageOverrideTag) ProtoMessage() {}

func (x *OuterMessageOverrideTag) ProtoReflect() protoreflect.Message {
	mi := &file_struct_tags_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessageOverrideTag.ProtoReflect.Descriptor instead.
func (*OuterMessageOverrideTag) Descriptor() ([]byte, []int) {
	return file_struct_tags_proto_rawDescGZIP(), []int{3}
}

type OuterMessageWithTags_InnerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" test:"value"`
}

func (x *OuterMessageWithTags_InnerMessage) Reset() {
	*x = OuterMessageWithTags_InnerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_tags_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OuterMessageWithTags_InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterMessageWithTags_InnerMessage) ProtoMessage() {}

func (x *OuterMessageWithTags_InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_struct_tags_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessageWithTags_InnerMessage.ProtoReflect.Descriptor instead.
func (*OuterMessageWithTags_InnerMessage) Descriptor() ([]byte, []int) {
	return file_struct_tags_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OuterMessageWithTags_InnerMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OuterMessageOverrideTag_InnerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1   string `protobuf:"bytes,1,opt,name=value1,proto3" json:"value1" test:"value"`
	Value2   string `protobuf:"bytes,2,opt,name=value2,proto3" json:"-" test:"value"`
	Value3   string `protobuf:"bytes,3,opt,name=value3,proto3" test:"value" json:"value"`
	Protobuf string `json:"protobuf,omitempty" protobuf:"bytes,4,opt,name=proto,proto3" test:"value"`
}

func (x *OuterMessageOverrideTag_InnerMessage) Reset() {
	*x = OuterMessageOverrideTag_InnerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_struct_tags_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OuterMessageOverrideTag_InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterMessageOverrideTag_InnerMessage) ProtoMessage() {}

func (x *OuterMessageOverrideTag_InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_struct_tags_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessageOverrideTag_InnerMessage.ProtoReflect.Descriptor instead.
func (*OuterMessageOverrideTag_InnerMessage) Descriptor() ([]byte, []int) {
	return file_struct_tags_proto_rawDescGZIP(), []int{3, 0}
}

func (x *OuterMessageOverrideTag_InnerMessage) GetValue1() string {
	if x != nil {
		return x.Value1
	}
	return ""
}

func (x *OuterMessageOverrideTag_InnerMessage) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

func (x *OuterMessageOverrideTag_InnerMessage) GetValue3() string {
	if x != nil {
		return x.Value3
	}
	return ""
}

func (x *OuterMessageOverrideTag_InnerMessage) GetProtobuf() string {
	if x != nil {
		return x.Protobuf
	}
	return ""
}

var File_struct_tags_proto protoreflect.FileDescriptor

var file_struct_tags_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x0e, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x54, 0x61, 0x67, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x13, 0xca, 0xb5, 0x03, 0x0f, 0xa2, 0x01, 0x0c, 0x74, 0x65, 0x73,
	0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x51, 0x0a, 0x14, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x54, 0x61, 0x67, 0x73, 0x1a, 0x39, 0x0a, 0x0c, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x13, 0xca, 0xb5, 0x03, 0x0f, 0xa2, 0x01, 0x0c,
	0x74, 0x65, 0x73, 0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x54, 0x61, 0x67, 0x12, 0x39,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x21,
	0xca, 0xb5, 0x03, 0x1d, 0xa2, 0x01, 0x1a, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x31, 0x22, 0x20, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x34, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1c, 0xca, 0xb5, 0x03, 0x18, 0xa2,
	0x01, 0x15, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x2d, 0x22, 0x20, 0x74, 0x65, 0x73, 0x74, 0x3a,
	0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x12,
	0x38, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x20, 0xca, 0xb5, 0x03, 0x1c, 0xa2, 0x01, 0x19, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x22, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x20, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x12, 0x58, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x3c, 0xca, 0xb5, 0x03,
	0x38, 0xa2, 0x01, 0x35, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3a, 0x22, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x2c, 0x34, 0x2c, 0x6f, 0x70, 0x74, 0x2c, 0x6e, 0x61, 0x6d, 0x65, 0x3d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x22, 0x20, 0x74, 0x65, 0x73,
	0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0xaf, 0x02, 0x0a, 0x17, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x54, 0x61, 0x67, 0x1a,
	0x93, 0x02, 0x0a, 0x0c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x39, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x21, 0xca, 0xb5, 0x03, 0x1d, 0xa2, 0x01, 0x1a, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x31, 0x22, 0x20, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x12, 0x34, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1c, 0xca, 0xb5, 0x03,
	0x18, 0xa2, 0x01, 0x15, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x2d, 0x22, 0x20, 0x74, 0x65, 0x73,
	0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0x12, 0x38, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x20, 0xca, 0xb5, 0x03, 0x1c, 0xa2, 0x01, 0x19, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x22,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x33, 0x12, 0x58, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x3c, 0xca,
	0xb5, 0x03, 0x38, 0xa2, 0x01, 0x35, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3a, 0x22,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x2c, 0x34, 0x2c, 0x6f, 0x70, 0x74, 0x2c, 0x6e, 0x61, 0x6d, 0x65,
	0x3d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33, 0x22, 0x20, 0x74,
	0x65, 0x73, 0x74, 0x3a, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_struct_tags_proto_rawDescOnce sync.Once
	file_struct_tags_proto_rawDescData = file_struct_tags_proto_rawDesc
)

func file_struct_tags_proto_rawDescGZIP() []byte {
	file_struct_tags_proto_rawDescOnce.Do(func() {
		file_struct_tags_proto_rawDescData = protoimpl.X.CompressGZIP(file_struct_tags_proto_rawDescData)
	})
	return file_struct_tags_proto_rawDescData
}

var file_struct_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_struct_tags_proto_goTypes = []interface{}{
	(*MessageWithTags)(nil),                      // 0: tests.message.MessageWithTags
	(*OuterMessageWithTags)(nil),                 // 1: tests.message.OuterMessageWithTags
	(*MessageWithOverrideTag)(nil),               // 2: tests.message.MessageWithOverrideTag
	(*OuterMessageOverrideTag)(nil),              // 3: tests.message.OuterMessageOverrideTag
	(*OuterMessageWithTags_InnerMessage)(nil),    // 4: tests.message.OuterMessageWithTags.InnerMessage
	(*OuterMessageOverrideTag_InnerMessage)(nil), // 5: tests.message.OuterMessageOverrideTag.InnerMessage
}
var file_struct_tags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_struct_tags_proto_init() }
func file_struct_tags_proto_init() {
	if File_struct_tags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_struct_tags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_struct_tags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OuterMessageWithTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_struct_tags_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageWithOverrideTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_struct_tags_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OuterMessageOverrideTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_struct_tags_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OuterMessageWithTags_InnerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_struct_tags_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OuterMessageOverrideTag_InnerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_struct_tags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_struct_tags_proto_goTypes,
		DependencyIndexes: file_struct_tags_proto_depIdxs,
		MessageInfos:      file_struct_tags_proto_msgTypes,
	}.Build()
	File_struct_tags_proto = out.File
	file_struct_tags_proto_rawDesc = nil
	file_struct_tags_proto_goTypes = nil
	file_struct_tags_proto_depIdxs = nil
}
